require([
    // 'jquery',
    // 'easyui',
    // 'easyui_lang_zh_CN',
    // 'jquery_cookie',
    // 'moment',
    // 'utils',
    // 'webuploader',
    // 'uploadercommon',
    // 'jquery_poshytip',
    // 'syExtEasyUI',
    // 'syExtJquery',
    // 'form2json',
    // 'gallery_introtour_ui_jq',
    // 'common',
    'fontsize',
    'cfg_header',
    'amsmovablerack_manage',
    'amsmovablerack_grid',
    'amsstorage_grid',
    'totemCabinet_cabinet',
    'cabinet_contr',
    'totemCabinet_cabinet',
    'cfg'

] )